// const.js
export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const VIEW_EMPLOYEE_DETAIL = 'VIEW_EMPLOYEE_DETAIL';
export const PAGINATION_CHANGE = 'PAGINATION_CHANGE';
